version: "3.9"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: api.metar.gg
      LETSENCRYPT_HOST: api.metar.gg
      LETSENCRYPT_EMAIL: api@metar.gg
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        MYSQL_DATABASE: metargg
volumes:
  db_data: {}

networks:
  default:
    external:
      name: nginx-proxy