version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: metargg
volumes:
  db_data: {}