// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"metar.gg/ent"
)

type StationWithDistance struct {
	// The distance in meters from the given location to the airport.
	Distance float64 `json:"distance"`
	// The METAR for the station.
	Station *ent.WeatherStation `json:"station"`
}
