// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"metar.gg/ent/predicate"
	"metar.gg/ent/temperaturedata"
)

// TemperatureDataQuery is the builder for querying TemperatureData entities.
type TemperatureDataQuery struct {
	config
	ctx        *QueryContext
	order      []temperaturedata.OrderOption
	inters     []Interceptor
	predicates []predicate.TemperatureData
	withFKs    bool
	loadTotal  []func(context.Context, []*TemperatureData) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TemperatureDataQuery builder.
func (tdq *TemperatureDataQuery) Where(ps ...predicate.TemperatureData) *TemperatureDataQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *TemperatureDataQuery) Limit(limit int) *TemperatureDataQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *TemperatureDataQuery) Offset(offset int) *TemperatureDataQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TemperatureDataQuery) Unique(unique bool) *TemperatureDataQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *TemperatureDataQuery) Order(o ...temperaturedata.OrderOption) *TemperatureDataQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// First returns the first TemperatureData entity from the query.
// Returns a *NotFoundError when no TemperatureData was found.
func (tdq *TemperatureDataQuery) First(ctx context.Context) (*TemperatureData, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{temperaturedata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TemperatureDataQuery) FirstX(ctx context.Context) *TemperatureData {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TemperatureData ID from the query.
// Returns a *NotFoundError when no TemperatureData ID was found.
func (tdq *TemperatureDataQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{temperaturedata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TemperatureDataQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TemperatureData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TemperatureData entity is found.
// Returns a *NotFoundError when no TemperatureData entities are found.
func (tdq *TemperatureDataQuery) Only(ctx context.Context) (*TemperatureData, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{temperaturedata.Label}
	default:
		return nil, &NotSingularError{temperaturedata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TemperatureDataQuery) OnlyX(ctx context.Context) *TemperatureData {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TemperatureData ID in the query.
// Returns a *NotSingularError when more than one TemperatureData ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TemperatureDataQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{temperaturedata.Label}
	default:
		err = &NotSingularError{temperaturedata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TemperatureDataQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TemperatureDataSlice.
func (tdq *TemperatureDataQuery) All(ctx context.Context) ([]*TemperatureData, error) {
	ctx = setContextOp(ctx, tdq.ctx, "All")
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TemperatureData, *TemperatureDataQuery]()
	return withInterceptors[[]*TemperatureData](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TemperatureDataQuery) AllX(ctx context.Context) []*TemperatureData {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TemperatureData IDs.
func (tdq *TemperatureDataQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, "IDs")
	if err = tdq.Select(temperaturedata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TemperatureDataQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TemperatureDataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Count")
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*TemperatureDataQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TemperatureDataQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TemperatureDataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Exist")
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TemperatureDataQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TemperatureDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TemperatureDataQuery) Clone() *TemperatureDataQuery {
	if tdq == nil {
		return nil
	}
	return &TemperatureDataQuery{
		config:     tdq.config,
		ctx:        tdq.ctx.Clone(),
		order:      append([]temperaturedata.OrderOption{}, tdq.order...),
		inters:     append([]Interceptor{}, tdq.inters...),
		predicates: append([]predicate.TemperatureData{}, tdq.predicates...),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ValidTime time.Time `json:"valid_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TemperatureData.Query().
//		GroupBy(temperaturedata.FieldValidTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *TemperatureDataQuery) GroupBy(field string, fields ...string) *TemperatureDataGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TemperatureDataGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = temperaturedata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ValidTime time.Time `json:"valid_time,omitempty"`
//	}
//
//	client.TemperatureData.Query().
//		Select(temperaturedata.FieldValidTime).
//		Scan(ctx, &v)
func (tdq *TemperatureDataQuery) Select(fields ...string) *TemperatureDataSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &TemperatureDataSelect{TemperatureDataQuery: tdq}
	sbuild.label = temperaturedata.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TemperatureDataSelect configured with the given aggregations.
func (tdq *TemperatureDataQuery) Aggregate(fns ...AggregateFunc) *TemperatureDataSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TemperatureDataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !temperaturedata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TemperatureDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TemperatureData, error) {
	var (
		nodes   = []*TemperatureData{}
		withFKs = tdq.withFKs
		_spec   = tdq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, temperaturedata.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TemperatureData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TemperatureData{config: tdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(tdq.modifiers) > 0 {
		_spec.Modifiers = tdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range tdq.loadTotal {
		if err := tdq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tdq *TemperatureDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	if len(tdq.modifiers) > 0 {
		_spec.Modifiers = tdq.modifiers
	}
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TemperatureDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(temperaturedata.Table, temperaturedata.Columns, sqlgraph.NewFieldSpec(temperaturedata.FieldID, field.TypeUUID))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, temperaturedata.FieldID)
		for i := range fields {
			if fields[i] != temperaturedata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TemperatureDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(temperaturedata.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = temperaturedata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tdq.modifiers {
		m(selector)
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tdq *TemperatureDataQuery) Modify(modifiers ...func(s *sql.Selector)) *TemperatureDataSelect {
	tdq.modifiers = append(tdq.modifiers, modifiers...)
	return tdq.Select()
}

// TemperatureDataGroupBy is the group-by builder for TemperatureData entities.
type TemperatureDataGroupBy struct {
	selector
	build *TemperatureDataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TemperatureDataGroupBy) Aggregate(fns ...AggregateFunc) *TemperatureDataGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *TemperatureDataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, "GroupBy")
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TemperatureDataQuery, *TemperatureDataGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *TemperatureDataGroupBy) sqlScan(ctx context.Context, root *TemperatureDataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TemperatureDataSelect is the builder for selecting fields of TemperatureData entities.
type TemperatureDataSelect struct {
	*TemperatureDataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TemperatureDataSelect) Aggregate(fns ...AggregateFunc) *TemperatureDataSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TemperatureDataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, "Select")
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TemperatureDataQuery, *TemperatureDataSelect](ctx, tds.TemperatureDataQuery, tds, tds.inters, v)
}

func (tds *TemperatureDataSelect) sqlScan(ctx context.Context, root *TemperatureDataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tds *TemperatureDataSelect) Modify(modifiers ...func(s *sql.Selector)) *TemperatureDataSelect {
	tds.modifiers = append(tds.modifiers, modifiers...)
	return tds
}
